apiVersion: v1
kind: Secret
data:
{{- range $k, $v := .Values.additionalEnv }}
  {{ $k }}: {{ $v | b64enc }}
{{- end }}
metadata:
  name: {{ include "extended-ceph-exporter.fullname" . }}
  labels:
    {{- include "extended-ceph-exporter.labels" . | nindent 4 }}
